### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by hippich**

### CODE REVIEW

**Comment by leeluolee** [comment]
:+1:   Good job. . . @hippich .   Huge changed files are the proofs of my dirty code.      :)

**Comment by leeluolee** [comment]
Release another day.  The changed code is   a little more than expected

**Comment by hippich** [comment]
This was prerequisite to start working on canUpdate part for me. i am going to work off your current develop to implement it.

**Comment by leeluolee** [comment]
Looking forward to that feature  .  :yum:

**Pull request merged**
